# Manages the input data to the NN
Inputs:

  # Load input arrays if enabled
  LOAD_ARRAYS : True
  # Save input arrays if enabled
  SAVE_ARRAYS : False
  ARRAYS_FILEPATH : "data.npz"
  
  # Variables to define from available information
  variables_to_define: 
    "met_px" : "met_pt * cos(met_phi)"
    "met_py" : "met_pt * sin(met_phi)"
  
  # columns used for tracks features
  trk_columns:
    - "trk_d0"
    - "trk_z0"
    - "trk_px"
    - "trk_py"
    - "trk_eta"
    - "trk_charge"
  
  # columns used for event-level features
  event_columns:
    - "met_px"
    - "met_py"
    - "nTrack"
    - "nJet"
  
  # columns used to build jet arrays
  jet_columns:
    - "jet_pt" 
    - "jet_eta" 
    - "jet_phi"
    - "jet_mass"

# Parametrise the NN architecture
Architecture:
  MAX_TRACKS: 16
  PHI_DIM: 64
  ATTENTION_HIDDEN_DIM: 8
  RHO_DIM: 8
  LATENT_DIM: 4

# Training settings  
Training:
  MAX_EVENTS: 100000
  BATCH_SIZE: 256
  N_EPOCHS: 6
  K_FOLDS : 5

  # For VAE networks
  STOP_RHO_GRADIENT: True
  BETA_KL_WEIGHT : 2 #0.1

  # For VICReg
  LAMBDA_INV : 1.0 # Invariance loss coeff
  LAMBDA_VAR : 1.0 # Variance loss coeff
  LAMBDA_COV : 1.0 # Covariance loss coeff
  GAMMA : 1.0 # Variance enforced by Variance term



  
